Repository Rakesh-ada/LearnEX, pull requests merged in 2025-05, with the labels that each got.

#1 Chatpdf update
  .env
  .env.example
  app/layout.tsx
  app/marketplace/page.tsx
  components/markdown-renderer.tsx
  components/pdf-viewer-with-ai.tsx
  lib/blockchain.ts
  lib/contract.ts
  styles/globals.css
  styles/pdf-viewer.css
Labels: Review effort 3/5

#3 Updated UI and added some sections
  app/page.tsx
Labels: Review effort 4/5

#2 Major updates and fix bugs
  components/pdf-viewer-with-ai.tsx
Labels: Review effort 2/5

#5 Organization video upload
  components/organization-tab.tsx
  components/pdf-viewer-with-ai.tsx
Labels: Review effort 1/5
